title: 一片叶
description: 一花一世界，一树一菩提.
author: Shangzhi Huang
avatar: /logo.png
email: ngzhio@gmail.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
permalink: /:title.html
# include子页面路径在_pages文件内
defaults:
  - scope:
      path: ""      
      type: "posts"
    values:
      layout: "post"
      author: "青红椒"
      image: "avatar.jpg"
      share: true
  - scope:
      path: ""      
      type: "pages"
    values:
      layout: "page"
      author: "QingHongJiao"
      image: "avatar.jpg"

twitter:
  username: ngzhio
  card: solarized
logo: logo.png
social:
  name: Shangzhi Huang
  links:
    - https://twitter.com
    - https://www.facebook.com
    - https://github.com
google_site_verification: u4WXQl0Eu66rsQox
lang: zh-Hans

# skin主题 白色，日出，日落，黑色（daylight，sunrise，sunset，midnight，）
skin: daylight
